resources:
    App\Entity\FinanceStatus:
        attributes:
            pagination_enabled: false
            normalization_context:
                groups: ['finance-read']
            denormalization_context:
                groups: ['finance-write']
            swagger_context: 
                groups: ['finance-read','finance-write']
        collectionOperations:
            get:
                method: 'GET'
            post:
                method: 'POST'

        itemOperations:
            get:
                method: 'GET'

            put:
                method: 'PUT'
