resources:
    App\Entity\NotificationUser:
        attributes:
            pagination_enabled: false
            normalization_context:
                groups: ['notification-read']
            denormalization_context:
                groups: ['notification-write']
        collectionOperations:
            get:
                method: 'GET'
                route_name: 'api_notification_get'

        itemOperations:
            get:
                method: 'GET'

            put:
                method: 'PUT'
