easy_admin:
    entities:    
        Home:
            class: App\Entity\Home
            label: menu.home
            list:
                title: menu.home
                fields:
                    - { property: 'id', label: 'id' }
                    - { property: 'name', label: 'name' }
                    - { property: 'address', label: 'address'}
                    - { property: 'updatedDate', label: 'updatedDate'}
                    - { property: 'createDate', label: 'createdDate'}
                    - { property: 'owner', label: 'owner'}
                    
            show:
                title: menu.home
                fields:
                    - { property: 'id', label: 'id' }
                    - { property: 'name', label: 'name' }
                    - { property: 'address', label: 'address'}
                    - { property: 'members', label: 'members' }
                    - { property: 'bills', label: 'bills'}
                    - { property: 'updatedDate', label: 'updatedDate'}
                    - { property: 'createDate', label: 'createdDate'}
                    - { property: 'owner', label: 'owner'}
                    - { property: 'requestNotif', label: 'notification'}
#
                    
                    
            edit:
                title: menu.home
                fields:
                    - { property: 'id', label: 'id' }
                    - { property: 'name', label: 'name' }
                    - { property: 'address', label: 'address'}
                    - { property: 'members', label: 'members' }
                    - { property: 'bills', label: 'bills'}
                    - { property: 'updatedDate', label: 'updatedDate'}
                    - { property: 'createDate', label: 'createdDate'}
