easy_admin:
    design:    
        menu:
            - { entity: User, icon: 'user' }
            - { entity: Device, icon: 'mobile' }
            - { entity: Home, icon: 'home' }
            - { entity: NotificationUser, icon: 'envelope' }
            - { entity: Notification, icon: 'envelope' }
            - { entity: FinanceStatus, icon: 'money' }
            - { entity: Income, icon: 'money' }
            - { label: 'API', route: 'api', icon: 'tasks'}