easy_admin:
    design:    
        menu:
            - { entity: User, icon: 'user' }
            - { entity: Device, icon: 'mobile' }
            - { entity: Home, icon: 'home' }
            - { label: 'API', route: 'api', icon: 'tasks'}