easy_admin:
    design:    
        menu:
            - { entity: User, icon: 'user' }
            - { entity: Device, icon: 'mobile' }
            - { entity: Home, icon: 'home' }
            - { entity: NotificationUser, icon: 'envelope' }
            - { entity: Notification, icon: 'bell' }
            - { entity: FinanceStatus, icon: 'book' }
            - { entity: BudgetCat, icon: 'atlas' }
            - { entity: Budget, icon: 'clipboard-list' }
            - { entity: Category, icon: 'folder-plus'}
            - { entity: Operation, icon: 'random'}
            - { label: 'API', route: 'api', icon: 'tasks'}
